### ISSUE TITLE
Caused by: groovy.lang.MissingPropertyException: Could not get unknown property 'buildFeatures' for object of type com.android.build.gradle.internal.dsl.BaseAppModuleExtension.

### ISSUE THREAD

**Issue by nuzulr24** [Abealkindy/JsoupWebScrap#1]
Sore min,
Sepertinya terjadi error ketika melakukan sinkronasi gradle. mungkin ada pencerahannya min ?
![image](https://user-images.githubusercontent.com/40730150/113123086-74caaf80-923e-11eb-8315-5a035094f8e0.png)

**Comment by Abealkindy** [comment]
sore juga, maaf baru bales gan. Versi android studio sama gradlenya udah yg latest kah?

**Comment by nuzulr24** [comment]
versi 3.36 sih gan, btw pnya agan ini versi latest yg berapa ?

**Comment by Abealkindy** [comment]
punyaku android studio versi 4.1.3 gan, versi gradlenya juga beda. Pilihannya cuma 2, update android studionya atau ganti kode di gradlenya, kalo mau ganti kode, tinggal ganti `android.buildFeatures.viewBinding = true` jadi ```
viewBinding {
            enabled = true
        }
``` ajh gan

**Comment by Abealkindy** [comment]
ini link referensinya gan
[Link referensi viewBinding](https://medium.com/androiddevelopers/use-view-binding-to-replace-findviewbyid-c83942471fc#:~:text=To%20enable%20view%20binding%2C%20configure,gradle%20file.&text=Once%20enabled%20for%20a%20project,work%20with%20your%20existing%20layouts.)

**Comment by nuzulr24** [comment]
sudah ku fix gan, eh iya.
ini masih development yak ? ku coba klik read manga pas tampil fragment loading dpt respon klo masih ditutup ya gan ?
2 fitur ini masih bisa dipakek buat ngebaca anime masih ya gan ?

tq sebelumnya.
maklum ane cuma paham web jadi pengen baca manga lwt aplikasi dri buatan android studio nya wkwk

**Comment by Abealkindy** [comment]
hmm, bukan masalah lagi dev atau nggak sih sebenernya gan. Karena ini scraping dan di websourcenya cloudflarenya lagi aktif, jadinya gak bisa masuk gan, sementara ini lagi nyuri2 waktu buat bikin cloudflare bypass sendiri, gak bisa ngandelin lib terus soalnya

**Comment by nuzulr24** [comment]
oalah begitu toh ternyata problem buat scrapping data dari web lewat android, cukup berbeda jauh dengan scrapping lewat web juga pas agan ngomong begini. oh iya mungkin bisa diinfoin tempat (file dan baris keberapa) agan bypass cloudflare manganya yg ada di project android nya itu. siapa tau ane bisa bantu agan juga buat cari cari bypass cloudflare nya gitu.

**Comment by Abealkindy** [comment]
library buat bypass cloudflarenya kupasang di line 39 dari class MainActivity.java gan, kalo gak mau ribet2 nyari di directory android studionya, bisa langsung liat di github via link ini
[lompat ke class tujuan](https://github.com/Abealkindy/JsoupWebScrap/blob/master/app/src/main/java/com/example/myapplication/activities/MainActivity.java)

**Comment by Abealkindy** [comment]
buat Java, khususnya Android, yg buat bypass cloudflare gitu gak banyak gan, sebelumnya pernah bikin sendiri juga, jadi tinggal rewrite lagi ajh, eheh
